### ISSUE TITLE
Empty dependencies declarations fail

### ISSUE THREAD

**Issue by mnordine** [thosakwe/pub_mediator#7]
```yaml
dependencies:
  package_name:
  another: any
```

I believe `package_name` dep would be `any`?
